### PR TITLE
refactor: use host network mode for dfclient

### PR DESCRIPTION
**Pull request by starnop**
Signed-off-by: Starnop <starnop@163.com>

We deploy `dfclient` as daemonset which means that every node in the cluster will run a pod `dfclient`, so the container runtime like `pouchcontainer`on each node set the local IP as its image proxy. In this case, the container does not need to be accessed through a service or ingress. So update the network mode to `hostNetwork`.

Thanks for the advice form @shenlanse ,refer to [link](https://github.com/dragonflyoss/helm-chart/pull/1#issuecomment-444735340)

### CODE REVIEW

**Comment by Starnop** [comment]
LGTM. 😃

**Comment by luisdavim** [comment]
I think this should be made optional through a flag in `values.yaml`

**Comment by starnop** [comment]
> I think this should be made optional through a flag in `values.yaml`

For `dragonfly`, we only allow proxies for local requests. So I think we just need the mode of `host network`. WDYT?

**Comment by luisdavim** [comment]
I think there's no harm in making it optional (small change) and it could be useful for situations where policies prevent the use of host network.

**Comment by starnop** [comment]
This is indeed feasible although I don't think it is necessary,. Then I will re-submit a new PR to do this, and close this PR firstly. 😄

**Pull request closed without merging**
