### PR TITLE
feature: add chart of supernode

### PR DESCRIPTION
**Pull request by starnop**
Signed-off-by: Starnop <starnop@163.com>

This is a base version of the chart of supernode. There should be a lot things to be done. Welcome to put forward your opinion, let's make it better together. 👍 

How to use it ?
```
# cd $GOPATH/src/github.com/dragonflyoss/helm-chart/dragonfly-supernode

// dry install
# helm install dragonfly-supernode --dry-run --debug

// install
# helm install dragonfly-supernode

// validate
# kubectl get pods
NAME                                                 READY     STATUS             RESTARTS   AGE
righteous-pig-dragonfly-supernode-5bf57ccc67-6j9mr   1/1       Running            0          1m

# kubectl get svc
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
righteous-pig-dragonfly-supernode   ClusterIP   10.109.200.105   <none>        8001/TCP,8002/TCP   1m

......
```

### CODE REVIEW

**Comment by BlueBlue-Lee** [comment]
I  want to know how to configure --registry-mirror param for docker, ClusterIP type service of dfclient seems not suitable, two reasons: (1) we have to configure coreDNS addr in host (2) when access dfclient-service-ip:service-port, will be probably redirected to other node.

**Comment by allencloud** [comment]
LGTM

**Comment by starnop** [comment]
> I want to know how to configure --registry-mirror param for docker, ClusterIP type service of dfclient seems not suitable, two reasons: (1) we have to configure coreDNS addr in host (2) when access dfclient-service-ip:service-port, will be probably redirected to other node.

1. Q: how to configure --registry-mirror param for docker?
    A: please refer to https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon
2. A: ClusterIP type is the default type, and you can easily modify it. Maybe it's a little bit better to use `NodePort` as default, WDYT? 

Thanks for your advice. ^_^

**Comment by starnop** [comment]
I will complete the docs ASAP.

**Comment by BlueBlue-Lee** [comment]
> > I want to know how to configure --registry-mirror param for docker, ClusterIP type service of dfclient seems not suitable, two reasons: (1) we have to configure coreDNS addr in host (2) when access dfclient-service-ip:service-port, will be probably redirected to other node.
> 
> 1. Q: how to configure --registry-mirror param for docker?
>    A: please refer to https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon
> 2. A: ClusterIP type is the default type, and you can easily modify it. Maybe it's a little bit better to use `NodePort` as default, WDYT?
> 
> Thanks for your advice. ^_^

Thanks. What I mean is that dfclient doesn't need service. Deploy dfclient with hostnetwork seems more suitable.

**Comment by starnop** [comment]
> > > I want to know how to configure --registry-mirror param for docker, ClusterIP type service of dfclient seems not suitable, two reasons: (1) we have to configure coreDNS addr in host (2) when access dfclient-service-ip:service-port, will be probably redirected to other node.
> > 
> > 
> > 
> > 1. Q: how to configure --registry-mirror param for docker?
> >    A: please refer to https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon
> > 2. A: ClusterIP type is the default type, and you can easily modify it. Maybe it's a little bit better to use `NodePort` as default, WDYT?
> > 
> > Thanks for your advice. ^_^
> 
> Thanks. What I mean is that dfclient doesn't need service. Deploy dfclient with hostnetwork seems more suitable.

I agree with you, and a [pull request](https://github.com/dragonflyoss/helm-chart/pull/2) has been submitted, thanks for your advice. Comments are welcomed and pull requests are better. ^_^

**Pull request merged**
